apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreoffice-deployment
  labels:
    app: libreoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreoffice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: libreoffice-template
      labels:
        app: libreoffice
    spec:
      containers:
      - name: libreoffice
        image: libreoffice/online:master
        env:
        - name: domain
          value: "libreoffice.k8s.phoenixit.ru"
        - name: username
          value: "admin"
        - name: password
          value: "qwerty$4"

---
apiVersion: v1
kind: Service
metadata:
  name: libreoffice-service
  labels:
    run: libreoffice
spec:
  selector:
    app: libreoffice
  ports:
  - name: http
    protocol: TCP
    port: 9980
    targetPort: 9980
  type: ClusterIP
  externalIPs:
  - 192.168.245.64

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: libreoffice-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"

spec:
  tls:
  - hosts:
    - libreoffice.k8s.phoenixit.ru
    secretName: phx2019
  rules:
  - host: libreoffice.k8s.phoenixit.ru
    http:
      paths:
      - backend:
          serviceName: libreoffice-service
          servicePort: 9980
