version: '3'
services:
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
  nginx:
    container_name: nginx-server
    image: nginx:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./onlyoffice_nginx.conf:/etc/nginx/conf.d/onlyoffice.conf
      - ./ssl:/etc/nginx/ssl
networks:
  onlyoffice:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.5.0.0/16
