apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
spec:
  rules:
  - host: grafana.k8s.srv.local
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - ip: 192.168.245.125
    - ip: 192.168.245.42
    - ip: 192.168.245.64
    - ip: 192.168.245.66
