apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora-deployment
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: collabora-template
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:latest
        env:
        - name: domain
          value: "collabora.phoenixit.ru"
#        - name: username
#          value: "admin"
#        - name: password
#          value: "qwerty$4"

---
apiVersion: v1
kind: Service
metadata:
  name: collabora-service
  labels:
    run: collabora
spec:
  selector:
    app: collabora
  ports:
  - name: http
    protocol: TCP
    port: 9980
    targetPort: 9980
  type: ClusterIP
  #externalIPs:
  #- 192.168.245.64

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: collabora-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"

spec:
  tls:
  - hosts:
    - collabora.phoenixit.ru
    secretName: phx2019
  rules:
  - host: collabora.phoenixit.ru
    http:
      paths:
      - backend:
          serviceName: collabora-service
          servicePort: 9980
